name: Test LINE Chat Analytics

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-v2-flask:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies for v2-flask
      run: |
        cd v2-flask
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test Flask app imports
      run: |
        cd v2-flask
        python -c "from flask_app import app; print('✅ Flask app imports successfully')"
        
    - name: Test Flask app startup
      run: |
        cd v2-flask
        python -c "
        from flask_app import app
        import threading
        import time
        import requests
        
        # Start Flask in background
        def run_app():
            app.run(host='127.0.0.1', port=5555, debug=False, use_reloader=False)
        
        thread = threading.Thread(target=run_app)
        thread.daemon = True
        thread.start()
        
        # Wait for startup
        time.sleep(3)
        
        try:
            # Test if server responds
            response = requests.get('http://127.0.0.1:5555/test', timeout=5)
            assert response.status_code == 200
            print('✅ Flask server responds correctly')
        except Exception as e:
            print(f'❌ Server test failed: {e}')
            exit(1)
        "
        
    - name: Test Thai language support
      run: |
        cd v2-flask
        python -c "
        try:
            from pythainlp import word_tokenize
            result = word_tokenize('สวัสดีครับ')
            assert len(result) > 0
            print('✅ Thai language support working')
        except ImportError:
            print('⚠️  Thai language support optional')
        except Exception as e:
            print(f'❌ Thai language test failed: {e}')
            exit(1)
        "

  # Optional: Test v1-streamlit compatibility
  test-v1-streamlit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Test v1-streamlit imports
      run: |
        cd v1-streamlit
        python -m pip install --upgrade pip
        # Test if basic imports work (without installing heavy dependencies)
        python -c "
        import pandas as pd
        print('✅ Basic imports work for v1')
        "
      continue-on-error: true  # v1 may have dependency issues
